export const ERROR_CODES = {
  // User/Auth related
  USER_EXISTS: "USER_EXISTS",
  WALLET_EXISTS: "WALLET_EXISTS",
  INVALID_REFERRAL: "INVALID_REFERRAL",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Referral related
  REFERRAL_CODE_GENERATION_FAILED: "REFERRAL_CODE_GENERATION_FAILED",
  REFERRAL_CODE_INVALID_FORMAT: "REFERRAL_CODE_INVALID_FORMAT",
  REFERRAL_CODE_NOT_FOUND: "REFERRAL_CODE_NOT_FOUND",

  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
};
